### ISSUE TITLE
add systemd units for node.js services

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#1]

**Comment by DerDakon** [comment]
API done, renderer to be done.

**Comment by DerDakon** [comment]
Tileserver done. Will open PRs to put the unit file templates in the repos for easier reuse.

**Comment by Nakaner** [comment]
@DerDakon Will you create a subdirectory in the OpenRailwayMap repository or here?

**Comment by DerDakon** [comment]
I'll put one in node-tileserver and the one for the API service in the OpenRailwayMap repo.
