### ISSUE TITLE
OSM data updating

### ISSUE THREAD

**Issue by ferrocarta** [OpenRailwayMap/server-admin#15]
It looks like updated data from OSM is no longer properly imported on ORM. See this example:
https://www.openrailwaymap.org/?lang=null&lat=40.74127439314326&lon=140.2353286743164&zoom=11&style=standard
The whole line from Hiroto (広戸) to Kawabe (川部) should appear in orange, it was tagged usage=main two months ago.

**Comment by EckhardM** [comment]
I am experiencing still the same issue. It seems that changes are not or only partly shown on the openrailwaymap.org map.  Look at https://www.openrailwaymap.org/?lang=null&lat=54.13036644919398&lon=12.078083753585815&zoom=16&style=standard the former railway is shown only partly and in a older version then in the OSM database.

**Comment by Nakaner** [comment]
This has been fixed by the new server which has been running for almost three weeks.
