### ISSUE TITLE
add script for style update

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#18]
Please add a script that I can run to deploy the current git code for both CartoCSS style and other code to the running instance. Can be 2 scripts if that is easier. Should probably end up in /etc/sudoers.d so I can just do "sudo /some/script" and everything works.

**Comment by Nakaner** [comment]
resolved by d160fc0cc68e1a97411ebd440fa84ec0bdc7482a, 3f2fa06fe18edecdc9fd3dc2e143c2929e5a2424, 67c9c93704281c7a84aadc21ecef6f87bdea34fc, 21ee2a36354c6191277682e2108a162bad6ca476
