### ISSUE TITLE
set reverse DNS

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#3]
$ host www.openrailwaymap.org
www.openrailwaymap.org has address 88.99.61.211
www.openrailwaymap.org has IPv6 address 2a01:4f8:10a:e03::2
$ host 88.99.61.211
211.61.99.88.in-addr.arpa domain name pointer static.211.61.99.88.clients.your-server.de.
$ host 2a01:4f8:10a:e03::2
Host 2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.3.0.e.0.a.0.1.0.8.f.4.0.1.0.a.2.ip6.arpa not found: 3(NXDOMAIN)

**Comment by Nakaner** [comment]
Without a proper reverse DNS, popular mail providers will not accept the emails.

**Comment by DerDakon** [comment]
Seems ok meanwhile.
