### ISSUE TITLE
tirex systemd services missing?

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#36]
We have these:

* tirex-tiledir-check@maxspeed.timer
* tirex-tiledir-check@signals.timer
* tirex-tiledir-check@standard.service
* tirex-tiledir-check@standard.timer

I wonder if we are missing at least the timer ones for gauge and electricity, and maybe the service one for almost all of them?

**Comment by Nakaner** [comment]
I think I forgot to add them when I added the other styles.

**Comment by DerDakon** [comment]
Should be generated by the ansible playbooks then, e.g. in some of the loops introduced in #30.
