### ISSUE TITLE
enable TLS for SMTP

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/server-admin#4]
Currently neither for incoming nor for outgoing SMTP connections encryption is used.

**Comment by DerDakon** [comment]
Should work now.

**Comment by rurseekatze** [comment]
Can you document your changes and commit the config file?

**Comment by DerDakon** [comment]
I think this is beyond the scope of the OpenRailwayMap repo. What I did was to ask the [Mozilla SSL config generator](https://ssl-config.mozilla.org/#server=postfix&server-version=2.10.1&config=intermediate&openssl-version=1.0.2k) for the Postfix version installed, append that to /etc/postfix/main.cf, and fix the path to the certificates to point at the webserver ones.

**Comment by DerDakon** [comment]
The necessary bits are in [ansible/roles/mail/templates/main.cf](https://github.com/OpenRailwayMap/server-admin/blob/master/ansible/roles/mail/templates/main.cf) since 4c492f14c6d57507ecd8254468e7a77af2638516 (smtpd_tls_*).
